# Introdução ao Numpy

**NumPy**: biblioteca de álgebra linear para Python. Quase todas as bibliotecas de Ciência de Dados acabam dependendo dela para alguma coisa.

Nesse post do [StackOverflow](http://stackoverflow.com/questions/993984/why-numpy-instead-of-python-lists) tem informações sobre por que você deseja usar numpy arrays em vez de listas.

O básico iremos ver aqui :)

## Qual a diferença entre Numpy e uma lista?

In [44]:
import numpy as np


np.random.seed(12345)

In [2]:
lista_normal = list(range(1000000))
array = np.arange(1000000)

In [4]:
type(array)

numpy.ndarray

In [5]:
%time for _ in range(10): array2 = array * 2
%time for _ in range(10): lista2 = [ x * 2 for x in lista_normal ]

CPU times: user 24.3 ms, sys: 14.6 ms, total: 38.8 ms
Wall time: 43.6 ms
CPU times: user 754 ms, sys: 269 ms, total: 1.02 s
Wall time: 2.02 s


## E como podemos interagir? Através dos Métodos e Atributos.

In [6]:
# atribuindo uma lista para variavel
lista =  [ 5, 2, 7 ]

In [7]:
lista * 2

[5, 2, 7, 5, 2, 7]

In [8]:
# para converter uma lista para um numpy array, nós utilizamos a np.array

lista = np.array(lista)
type(lista)

numpy.ndarray

In [10]:
 print(lista * 2)

[10  4 14]


In [11]:
valores = [ 10, 20, 30 ]
qtdades = [  2,  8,  5 ]

valores * qtdades

TypeError: can't multiply sequence by non-int of type 'list'

In [12]:
valores = np.array(valores)
qtdades = np.array(qtdades)

valores * qtdades

array([ 20, 160, 150])

In [13]:
conj_1 = [  2,  8,  5 ]
conj_2 = [  4,  6 ]

np.array(conj_1) * np.array(conj_2)

ValueError: operands could not be broadcast together with shapes (3,) (2,) 

In [14]:
nova_lista = np.array([ 10 , 'string', True ])

In [15]:
type(nova_lista)

numpy.ndarray

In [16]:
nova_lista

array(['10', 'string', 'True'], dtype='<U21')

In [17]:
nova_lista * 2

UFuncTypeError: ufunc 'multiply' did not contain a loop with signature matching types (dtype('<U21'), dtype('<U21')) -> dtype('<U21')

In [19]:
# metódo shape que é responsável por mostrar o formato de dimensão
valores.shape

(3,)

In [20]:
matriz = np.array([ (10,20, 30) , (4,5,6) ])
matriz

array([[10, 20, 30],
       [ 4,  5,  6]])

In [21]:
matriz.shape

(2, 3)

In [22]:
# a outra forma de validar a dimensao é usando o .ndim
matriz.ndim

2

In [23]:
valores.ndim

1

In [34]:
# operacoes possiveis com obj numpy
matriz.min()
matriz.max()
matriz.mean()
matriz.std()
matriz.cumsum()
matriz.sum()

75

In [33]:
# itemsize é usado para saber o tamanho em bytes do objeto
print(matriz.itemsize)

#  e o .size retorna a quantidade de elementos dentro do objeto

print(matriz.size)

8
6


In [35]:
# Reshape do objeto numpy, pega a ultima linha e joga o seu conteudo ao final da primeira lista
matriz.reshape(-1)

array([10, 20, 30,  4,  5,  6])

In [37]:
# Trasnspor a matriz
print(matriz.shape)
print(matriz.T.shape)

(2, 3)
(3, 2)


In [40]:
matriz_t = matriz.T
matriz_t

array([[10,  4],
       [20,  5],
       [30,  6]])

In [41]:
matriz_t.reshape(2,3)

array([[10,  4, 20],
       [ 5, 30,  6]])

In [43]:
matriz_randomica = np.random.random((5,3))
matriz_randomica.mean()

0.6654535992701277

In [45]:
lista_operacoes = np.array([5,8,2])
lista_operacoes 

array([5, 8, 2])

### Inserir e Remover elementos de um array

In [46]:
lista_operacoes = np.insert(lista_operacoes,0, 10)
lista_operacoes

array([10,  5,  8,  2])

In [48]:
lista_operacoes = np.delete(lista_operacoes, 2)
lista_operacoes

array([10,  5])

### Acessando posiçoes e filtrando dados

In [49]:
matriz

array([[10, 20, 30],
       [ 4,  5,  6]])

In [50]:
# retornar o numero 5 da matriz
matriz[1][1]

5

In [52]:
matriz[ :1 , :2 ]

array([[10, 20]])

In [54]:
matriz > 5

array([[ True,  True,  True],
       [False, False,  True]])

In [55]:
matriz[ matriz > 5 ]

array([10, 20, 30,  6])

In [56]:
#Filtrando elementos
nomes = np.array([
    'maria','joao', 'pedro', 'maria', 'carlos'
])

nomes

array(['maria', 'joao', 'pedro', 'maria', 'carlos'], dtype='<U6')

In [57]:
nomes == 'joao'


array([False,  True, False, False, False])

In [58]:
nomes != 'maria'

array([False,  True,  True, False,  True])

In [59]:
nomes[ nomes != 'maria' ]

array(['joao', 'pedro', 'carlos'], dtype='<U6')

In [60]:
# Tipos de matrizes que viámos em aula
# matriz de zeros
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [61]:
# matriz de numeros 1
np.ones(4)

array([1., 1., 1., 1.])

In [63]:
#matriz identidade
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [64]:
# array com o mesmo espaçamento entre os elementos
np.linspace(10,50,5)

array([10., 20., 30., 40., 50.])

In [68]:
np.linspace(10,50,3)

array([10., 30., 50.])