# Introdução ao Numpy

**NumPy**: biblioteca de álgebra linear para Python. Quase todas as bibliotecas de Ciência de Dados acabam dependendo dela para alguma coisa.

Nesse post do [StackOverflow](http://stackoverflow.com/questions/993984/why-numpy-instead-of-python-lists) tem informações sobre por que você deseja usar numpy arrays em vez de listas.

O básico iremos ver aqui :)

## Qual a diferença entre Numpy e uma lista?

In [1]:
# Importar a biblioteca de trabalho
import numpy as np
np.random.seed(12345)

In [2]:
array_np = np.arange(1000000)
lista_normal = list(range(1000000))

In [6]:
type(array_np)

numpy.ndarray

In [7]:
%time for _ in range(10): array2 = array_np * 2
%time for _ in range(10): list2 = [x * 2 for x in lista_normal]

CPU times: user 18.7 ms, sys: 15.9 ms, total: 34.6 ms
Wall time: 33.3 ms
CPU times: user 699 ms, sys: 144 ms, total: 843 ms
Wall time: 842 ms


## E como podemos interagir? Através dos Métodos e Atributos.

In [21]:
# atribuindo uma lista para variavel
lista = [5,2,7]

In [13]:
# Multiplicando a lista por 2, porém a gente tem a duplicação dos elementos
lista * 2

[5, 2, 7, 5, 2, 7]

In [14]:
# Conversao da variavel do tipo lista para uma variavel do tipo numpy array
lista = np.array(lista)

In [15]:
type(lista)

numpy.ndarray

In [22]:
# Multiplicando o valor da lista por 2 (cada elemento de forma individual) e armazenando em uma segunda variavel
lista_x2 = lista * 2

In [23]:
lista_x2

[5, 2, 7, 5, 2, 7]

In [24]:
valor_unit = [10,50,30]
qtd_itens = [2,5,8]

In [25]:
valor_unit * qtd_itens

TypeError: can't multiply sequence by non-int of type 'list'

In [26]:
valor_unit = np.array(valor_unit)
qtd_itens = np.array(qtd_itens)

In [27]:
valor_unit * qtd_itens

array([ 20, 250, 240])

In [28]:
conj_1 = [2,4,6,8]
conj_2 = [3,5]

In [30]:
np.array(conj_1) * np.array(conj_2)

ValueError: operands could not be broadcast together with shapes (4,) (2,) 

In [31]:
nova_lista = np.array([1, 'texto', False])

In [32]:
type(nova_lista)

numpy.ndarray

In [33]:
nova_lista

array(['1', 'texto', 'False'], dtype='<U21')

In [34]:
nova_lista * 2

UFuncTypeError: ufunc 'multiply' did not contain a loop with signature matching types (dtype('<U21'), dtype('<U21')) -> dtype('<U21')

In [35]:
# metodo para verificar o formato (dimensao) do objeto array
valor_unit.shape

(3,)

In [36]:
carrinho = np.array(
                    [
                        (10,50,30),
                        (2,5,8)
                    ]
                    )

In [37]:
carrinho

array([[10, 50, 30],
       [ 2,  5,  8]])

In [38]:
carrinho.shape

(2, 3)

In [39]:
#como validar a qtd de dimensoes do objeto
carrinho.ndim

2

In [40]:
valor_unit.ndim

1

In [43]:
# retornando o menor valor, o maior valor do conjunto
print(carrinho.min())
print(carrinho.max())

2
50


In [45]:
# qual o valor medio, desvio padrao e a soma acumulada
print(carrinho.mean())
print(carrinho.std())
print(carrinho.cumsum())

17.5
17.10506747526397
[ 10  60  90  92  97 105]


In [46]:
carrinho.itemsize

8

In [47]:
#soma de todos os itens dentro do array
carrinho.sum()

105

In [48]:
# converto uma matriz para um array, onde cada linha 
# a partir da primeira vai sendo adicionada ao final da primeira linha
carrinho.reshape(-1)

array([10, 50, 30,  2,  5,  8])

In [49]:
carrinho.ndim

2

In [51]:
carr_t = carrinho.T

In [52]:
carr_t.shape

(3, 2)

In [53]:
carrinho.shape

(2, 3)

In [55]:
carrinho.reshape(3,2)

array([[10, 50],
       [30,  2],
       [ 5,  8]])

In [58]:
matriz_dados = np.random.random((5,3))

In [59]:
matriz_dadosprint(carrinho.mean())

array([[0.65641118, 0.80981255, 0.87217591],
       [0.9646476 , 0.72368535, 0.64247533],
       [0.71745362, 0.46759901, 0.32558468],
       [0.43964461, 0.72968908, 0.99401459],
       [0.67687371, 0.79082252, 0.17091426]])

In [60]:
carrinho

array([[10, 50, 30],
       [ 2,  5,  8]])

In [61]:
carrinho = np.insert(carrinho,0,11)

In [62]:
carrinho

array([11, 10, 50, 30,  2,  5,  8])

In [63]:
carrinho = np.delete(carrinho,[0])

In [64]:
carrinho

array([10, 50, 30,  2,  5,  8])

In [69]:
np.savetxt("meu_carrinho.txt", carrinho)

In [70]:
!cat meu_carrinho.txt

1.000000000000000000e+01
5.000000000000000000e+01
3.000000000000000000e+01
2.000000000000000000e+00
5.000000000000000000e+00
8.000000000000000000e+00


In [71]:
!pwd

/home/valli/repos/ensino/ext-manip-dados/aulas


In [72]:
carrinho

array([10, 50, 30,  2,  5,  8])

In [73]:
carrinho2 = np.array(
                    [
                        (10,50,30),
                        (2,5,8)
                    ]
                    )

In [74]:
carrinho2

array([[10, 50, 30],
       [ 2,  5,  8]])

In [75]:
carrinho2[1][1]

5

In [76]:
carrinho2[0][2]

30

In [78]:
carrinho2[:,:2]

array([[10, 50],
       [ 2,  5]])

In [79]:
#Filtrando elementos
carrinho2 > 5

array([[ True,  True,  True],
       [False, False,  True]])

In [80]:
carrinho2[carrinho2 > 5]

array([10, 50, 30,  8])

In [81]:
nomes = np.array(['Bob', 'Joe', 'Will','Joe','Joe', 'Will'])

In [83]:
nomes == 'Joe'

array([False,  True, False,  True,  True, False])

In [84]:
nomes != 'Will'

array([ True,  True, False,  True,  True, False])

In [85]:
nomes[nomes != 'Will']

array(['Bob', 'Joe', 'Joe', 'Joe'], dtype='<U4')

In [86]:
# Tipos de matrizes que viámos em aula
# matriz de zeros
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [87]:
# matriz de numeros 1
np.ones(4)

array([1., 1., 1., 1.])

In [88]:
#matriz identidade
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [91]:
# array com o mesmo espaçamento entre os elementos
np.linspace(10,30,5)

array([10., 15., 20., 25., 30.])