Ex1.: importar a biblioteca numpy

In [1]:
import numpy as np

Ex2.: crie uma matriz de zeros contendo 20 elementos

In [2]:
np.zeros(20)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0.])

In [3]:
np.zeros((4,5)) 

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

Ex3: criar uma matriz com 10 numeros 5

In [4]:
np.ones(10)*5

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

Ex4: criar um array de inteiros de 10 até 40

In [6]:
np.arange(10,41)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40])

Ex5: array de numeros pares de 10 até 30

In [7]:
np.arange(10,31,2)

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30])